site_name: Marshmallow Generator

pages:
- Home: 'index.md'
- Aus dem alten Wiki: 
    - Anwenderdokumentation: 'AusWiki/Home.md'
- Getting Started:
    - Installing:
        - Installation Kitodo.Production 3.x: 'GettingStarted/installing/Installationsanleitung-für-Kitodo.Production-3.x.md'

